In [1]:
from fuvtds_base_class import FUVTDSBase
import numpy as np

In [2]:
x = FUVTDSBase(PIDs='fuvtds_analysis_list.dat')

  0%|          | 0/1766 [00:00<?, ?it/s]

+++ Scaling LP4 to LP3 using data from datasets: /grp/hst/cos2/cosmo/14854/ldcv20eyq_x1d.fits.gz /grp/hst/cos2/cosmo/14854/ldcv22wxq_x1d.fits.gz
+++ Scaling LP3 to LP4 using data from datasets: /grp/hst/cos2/cosmo/14854/ldcv22wxq_x1d.fits.gz /grp/hst/cos2/cosmo/14854/ldcv20eyq_x1d.fits.gz
+++ Scaling LP3 to LP2 using data from datasets: /grp/hst/cos2/cosmo/13967/lcqz03osq_x1d.fits.gz /grp/hst/cos2/cosmo/13967/lcqz04iiq_x1d.fits.gz
+++ Scaling LP2 to LP1 using data from datasets: /grp/hst/cos2/cosmo/12806/lbxmt1nxq_x1d.fits.gz /grp/hst/cos2/cosmo/12806/lbxm1bvsq_x1d.fits.gz
+++ Scaling LP4 to LP3 using data from datasets: /grp/hst/cos2/cosmo/14854/ldcv20elq_x1d.fits.gz /grp/hst/cos2/cosmo/14854/ldcv22wpq_x1d.fits.gz
+++ Scaling LP3 to LP2 using data from datasets: /grp/hst/cos2/cosmo/13967/lcqz03ogq_x1d.fits.gz /grp/hst/cos2/cosmo/13967/lcqz04h8q_x1d.fits.gz
+++ Scaling LP6 to LP4 using data from datasets: /grp/hst/cos2/cosmo/16830/ler15akzq_x1d.fits.gz /grp/hst/cos2/cosmo/16830/ler15am

In [3]:
table = x.tables

In [4]:
scaled_table = x.scale_to_1(1222, 'FUVB', table)

In [5]:
scaled_table['large_scaled_net'][:,0]

array([1.01517164, 1.01934578, 1.01344964, 1.02301793, 1.01894757,
       1.0175872 , 1.017772  , 1.01691364, 1.02228409, 1.01979067,
       1.01806168, 1.03276828, 1.03193953, 1.0373034 , 1.03134218,
       1.03325228, 1.02801544, 1.03743928, 1.02911587, 1.04242333,
       1.03434552, 1.03266768, 1.02561419, 1.02561419, 1.02309789,
       1.01359745, 1.0123774 , 1.00814336, 1.01093135, 1.01304547,
       1.00408108, 1.005092  , 0.99964004, 1.01621283, 1.00409792,
       1.00791803, 1.0063318 , 1.00432339, 1.00299678, 0.99615889,
       0.99615889, 0.99516091, 0.99238678, 0.99107487, 0.97791   ,
       0.98805623, 0.9854469 , 0.98158627, 0.97865242, 0.97013132,
       0.96992938, 0.96723139, 0.96881191, 0.9635009 , 0.96471937,
       0.95990763, 0.95845427, 0.95825438, 0.96023072, 0.95724818,
       0.95487291, 0.95205295, 0.94846512, 0.94851319, 0.94653378,
       0.94820341, 0.94741259, 0.94286882, 0.94687581, 0.94883472,
       0.94289611, 0.94635192, 0.93739505, 0.93317481, 0.93121

In [6]:
scaled_table['large_scaled_stdev'][:,0]

array([0.00518098, 0.00524139, 0.00522077, 0.00524722, 0.00524463,
       0.0052258 , 0.00522679, 0.00522367, 0.00525783, 0.00524384,
       0.00525807, 0.00528028, 0.0052585 , 0.00531154, 0.00527239,
       0.00527795, 0.00526549, 0.00531184, 0.00528221, 0.00534134,
       0.00529808, 0.00530061, 0.00526767, 0.0091422 , 0.00913078,
       0.00904141, 0.00903594, 0.00899954, 0.00902422, 0.00904228,
       0.00896879, 0.00898826, 0.00894348, 0.00908078, 0.00897312,
       0.00900899, 0.00899359, 0.00896856, 0.00898282, 0.00892582,
       0.01147945, 0.01145271, 0.01142412, 0.01141026, 0.01129031,
       0.01138085, 0.01134747, 0.01131752, 0.01128222, 0.01121629,
       0.01121648, 0.01118303, 0.01120315, 0.01115624, 0.01116323,
       0.01111266, 0.01109388, 0.01109885, 0.01111017, 0.01107961,
       0.01107384, 0.0110354 , 0.01099577, 0.01099863, 0.01097504,
       0.01099829, 0.01098218, 0.01094085, 0.01095984, 0.0109794 ,
       0.01091635, 0.01095495, 0.01085115, 0.01080224, 0.01078

In [7]:
net = np.array([[0.2, 0.3], [0.4, 0.5], [0.6, 0.7]])

In [8]:
net[1]

array([0.4, 0.5])

In [9]:
sum(net)

array([1.2, 1.5])